name: Run Zia Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps (optional)
        run: pip install -r requirements.txt || true

      - name: Build Zia (native)
        run: make build

      - name: Make test runner executable
        run: chmod +x ./tests/run_tests.py

      - name: Run Zia tests
        run: ./tests/run_tests.py ./zia.out ./tests --html ./tests/results.json

      - name: Install Jinja2 (Python library)
        run: pip install Jinja2

      - name: Run Zia report generator
        run: python3 ./tests/generate_html_report.py

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Convert HTML report to PDF
        run: wkhtmltopdf ./tests/test_report.html ./tests/test_report.pdf

      - name: Upload test report PDF
        uses: actions/upload-artifact@v4
        with:
          name: zia-test-report
          path: ./tests/test_report.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build_wasm