name: Run Zia Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps (optional)
        run: pip install -r requirements.txt || true

      - name: Build Zia (native)
        run: make build

      - name: Make test runner executable
        run: chmod +x ./tests/run_tests.py

      - name: Run Zia tests
        run: ./tests/run_tests.py ./zia.out ./tests
